var dummyData = {
        "Crear post":"<div class=\"containe\"><img src=\"../images/hospederia-de-alesves.gif\"><form action=\"queries/cambia_precios.php?site=workers\" method=\"post\"><div class=\"row\"><div class=\"col-25\"><label for=\"fname\">Título</label></div><div class=\"col-75\"><input type=\"text\" id=\"fname\" name=\"titulo\" placeholder=\"Indique título\"></div></div><div class=\"row\"><div class=\"col-25\"><label for=\"imagen\">Imagen</label></div><div class=\"col-75\"><input type=\"text\" id=\"imagen\" name=\"imagen\" placeholder=\"Escriba: 'images/' + el nombre del archivo completo\"></div></div><div class=\"row\"><div class=\"col-25\"><label for=\"t1\">Texto principal:</label></div><div class=\"col-75\"><textarea id=\"t1\" name=\"texto1\" placeholder=\"Para crear un salto de línea teclee '<br>'\"></textarea></div></div><div class=\"row\"><div class=\"col-25\"><label for=\"subject\">Texto entre comillas:</label></div><div class=\"col-75\"><textarea id=\"subject\" name=\"texto2\" placeholder=\"Para crear un salto de línea teclee '<br>'\"></textarea></div>"+
                "</div><div class=\"row\"><div class=\"col-25\"><label for=\"subject2\">Texto entre comillas:</label></div><div class=\"col-75\"><textarea id=\"subject2\" name=\"texto3\" placeholder=\"Para crear un salto de línea teclee '<br>'\"></textarea></div></div><div class=\"row\"><div class=\"col-25\"><label for=\"etiquetas\">Etiquetas:</label></div><div class=\"col-75\"><input id=\"etiquetas\" name=\"et1\"><input id=\"subject2\" name=\"et2\"><input id=\"subject2\" name=\"et3\"></div></div><div class=\"row\"><input type=\"submit\" value=\"Enviar\"></div></form></div>",
        "Por numero habitacion":"<div class=\"containe\"><img src=\"../images/hospederia-de-alesves.gif\" class=\"imagen\"><form method=\"post\" action=\"queries/cambia_precios.php?cambia=numero\"><label>Seleccione nº de habitación:</label><br><select  name=\"numero\"><option value=\"101\">101</option><option value=\"102\">102</option><option value=\"103\">103</option><option value=\"104\">104</option><option value=\"105\">105</option><option value=\"201\">201</option><option value=\"202\">202</option><option value=\"203\">203</option><option value=\"204\">204</option><option value=\"205\">205</option><option value=\"206\">206</option></select><br><br><label>Indique precio habitación:</label><br><input name=\"price\" type=\"number\"><br><br><input type=\"submit\" class=\"btn btn-success\"></form></div>",
        "Por tipo de habitacion":"<div class=\"containe\"><img src=\"../images/hospederia-de-alesves.gif\" class=\"imagen\"><form method=\"post\" action=\"queries/cambia_precios.php?cambia=tipo\"><label>Seleccione tipo de habitación:</label><br><select  name=\"tipo\"><option value=\"individual\">Individual</option><option value=\"doble\">Doble</option><option value=\"triple\">Triple</option><option value=\"superior\">Superior</option><option value=\"familiar\">Familiar</option><br><br><label>Indique precio habitación:</label><br><input name=\"precio\" type=\"number\"><br><br><input type=\"submit\"></form></div>",      
        "Cambiar disponibilidad":"<div class=\"containe\"><img src=\"../images/hospederia-de-alesves.gif\" class=\"imagen\"><form class=\"login-form\" method=\"post\" action=\"queries/cambia_precios.php?cambia=disponibilidad\"><label>Seleccione habitación:</label><br><select  name=\"disp\"><option value=\"101\">101</option><option value=\"102\">102</option><option value=\"103\">103</option><option value=\"104\">104</option><option value=\"105\">105</option><option value=\"201\">201</option><option value=\"202\">202</option><option value=\"203\">203</option><option value=\"204\">204</option><option value=\"205\">205</option><option value=\"206\">206</option></select><input type=\"submit\" class=\"btn btn-success\"></form></div>",
        "Nueva reserva":"<div class=\"containe\">"+
                                "<img src=\"../images/hospederia-de-alesves.gif\">"+
                                "<form action=\"../puente_bookin.php?site=workers\" method=\"post\">"+
                                "<div class=\"row\"><div class=\"col-25\">"+
                                "<label for=\"fname\" style=\"float:left;\">Nombre:</label></div><div class=\"col-75\"><input type=\"text\" id=\"fname\" name=\"nombre\" placeholder=\"Indique nombre del cliente\"></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+
                                "<label for=\"imagen\" style=\"float:left;\">Apellidos:</label></div><div class=\"col-75\"><input type=\"text\" id=\"imagen\" name=\"apellidos\" placeholder=\"Indique ambos apellidos del cliente\"></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+
                                "<label for=\"t1\" style=\"float:left;\">Nº teléfono:</label></div><div class=\"col-75\"><input type=\"text\" id=\"t1\" name=\"telefono\" placeholder=\"Indique nº de teléfono cliente\"></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+
                                "<label for=\"subject\" style=\"float:left;\">DNI:</label></div><div class=\"col-75\"><input type=\"text\" id=\"subject\" name=\"dni\" placeholder=\"Indique DNI cliente\"></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+ 
                                "<label for=\"habitacion\" style=\"float:left;\">Indique tipo de habitación:</label></div><div class=\"col-75\"><select id=\"habitacion\" name=\"tipo\"><option value=\"individual\">Individual</option><option value=\"doble\">Doble</option><option value=\"superior\">Superior</option><option value=\"triple\">Triple</option><option value=\"familiar\">Familiar</option></select></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+ 
                                "<label for=\"llegada\" style=\"float:left;\">Llegada:</label></div><div class=\"col-75\"><input type=\"date\" name=\"llegada\" id=\"llegada\"></div>"+
                                "</div>"+
                                "<div class=\"row\"><div class=\"col-25\">"+ 
                                "<label for=\"salida\" style=\"float:left;\">Salida:</label></div><div class=\"col-75\"><input type=\"date\" name=\"salida\" id=\"salida\"></div>"+
                                "</div>"+
                                "<input type=\"submit\"><br>"+
                        "</div>",
        "Borrar post":"<div class=\"form\"><img src=\"../images/hospederia-de-alesves.gif\" class=\"imagen\"><form method=\"post\" action=\"queries/cambia_precios.php?borra=post\"><label>Indique el título del post a borrar</label><br><input type=\"text\" name=\"post\" placeholder=\"Copie y pegue para evitar errores\"><input type=\"submit\" class=\"btn btn-success\"></form><br></div>",
        "Borrar comentarios":"<div class=\"\"><form class=\"containe\" method=\"post\" action=\"queries/cambia_precios.php?borra=comentario\"><label for=\"titulo_post\" style=\"float:left;\">Indique el título del post que donde se encuentra el comentario:</label><input id=\"titulo_post\" name=\"post\" type=\"text\" placeholder=\"Copie y pegue para evitar errores\"><label for=\"nombre\" style=\"float:left;\">Indique nombre de quien escribió el comentario:</label><input type=\"text\" id=\"nombre\" name=\"nombre\" placeholder=\"Copie y pegue para evitar errores\"><input type=\"submit\"><br></form><br></div>"
};
